addons:
  sonarcloud:
    organization: "quike-github"
    token:
      secure: "cJ5P1W0foQy5PZUcfQ5HtUQjFzMHvMdO4Ujf6L7oNJFW8MMV9jShZjxbluCepNpHdIfNNWZ0ow8o0CSGXzZmJyvWmA6wO0HbZawb3yb/5f4uAq00qO92YN5kstMbiaVkLqIAJhSwc45lE1oLjcBSIMh8QswkPwJjWUee5gLTNoX37v8RQ0DF9fcjL7lZq9dG25ND1lrLqI4mqrSJ7rCeAJsVq3zFghQ7B6V1pdk/CtZCAlEzhg+dAhUJUv8k7nIJ6ZzzsdC4LUMkzNy5yTL9t1Kwq7hFJN2YQloMDJHDmSijErFQjg55LCuly3IvtpkFXs9ukaPSR4C1XnUuWAZTJKXiPfNkdtVaNuSBZmzjgn2vEL/biEnlb3p4b4reiEWNkZSbpm+a0O72GMDbh/Z9H+YzMQMTz3BQ2el/wC+wwcbdqHuFPDhk9JtdpFzg0qILTH91B/H8N6C6gFJI6KLSKdkmCGUhttwGVTAuoc1bf0JD0vShQQTEw4P2Vq2EpTflhjY3ha6rkL8cemahnyEk/84ifbKEZiFFqdNBNMyYtnuJGiyMj4bgYwVYBUh6YawQCCM0L/hPU2KwpD5ilYgtXkkJ45VSGVheziTeF0bQZGdvxngACvhMD2M5gpppM3Xhekt/D2qL+PXljOVXCMXvvD4WEeYRz7ijQnvQ0CFT+Tc="

language: java

script:
  - sonar-scanner
